T_base_link__base_footprint:
  cols: 4
  data:
  - '1.000'
  - '0.000'
  - '0.000'
  - '0.000'
  - '0.000'
  - '1.000'
  - '0.000'
  - '0.000'
  - '0.000'
  - '0.000'
  - '1.000'
  - '-0.132'
  - '0.000'
  - '0.000'
  - '0.000'
  - '1.000'
  rows: 4
T_base_link__os_sensor:
  cols: 4
  data:
  - '1.000'
  - '0.000'
  - '0.000'
  - '0.081'
  - '0.000'
  - '1.000'
  - '0.000'
  - '0.000'
  - '0.000'
  - '0.000'
  - '1.000'
  - '0.545'
  - '0.000'
  - '0.000'
  - '0.000'
  - '1.000'
  rows: 4
T_os_sensor__realsense_front:
  cols: 4
  data:
  - 0.0
  - -1.0
  - 0.0
  - 0.017
  - 0.0
  - -0.0
  - -1.0
  - -0.188
  - 1.0
  - 0.0
  - 0.0
  - -0.311
  - 0.0
  - 0.0
  - 0.0
  - 1.0
  rows: 4
T_os_sensor__realsense_left:
  cols: 4
  data:
  - 1.0
  - -0.001
  - -0.0
  - 0.018
  - 0.0
  - -0.0
  - -1.0
  - -0.187
  - 0.001
  - 1.0
  - -0.0
  - -0.211
  - 0.0
  - 0.0
  - 0.0
  - 1.0
  rows: 4
T_os_sensor__realsense_rear:
  cols: 4
  data:
  - -0.002
  - 1.0
  - 0.0
  - 0.017
  - -0.0
  - 0.0
  - -1.0
  - -0.188
  - -1.0
  - -0.002
  - 0.0
  - -0.311
  - 0.0
  - 0.0
  - 0.0
  - 1.0
  rows: 4
T_os_sensor__realsense_right:
  cols: 4
  data:
  - -1.0
  - -0.001
  - 0.0
  - 0.017
  - 0.0
  - -0.0
  - -1.0
  - -0.188
  - 0.001
  - -1.0
  - 0.0
  - -0.211
  - 0.0
  - 0.0
  - 0.0
  - 1.0
  rows: 4
